# -*- coding: utf-8 -*-
"""analisis_churn_telco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWqxU-mkzfEwYtBTeyOjOTpCAYCaW5E0

# Analisis Customer Churn Telco


Notebook ini melakukan: data cleaning → exploratory data analysis (EDA) → perhitungan churn rate per segmen → 4 chart insight → draft memo insight.

## 0. Setup & Load Data
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

INPUT_FILE = "telco_churn.csv"
OUTPUT_DIR = "output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

df = pd.read_csv(INPUT_FILE)
print(f"Data awal: {df.shape[0]} baris, {df.shape[1]} kolom")
df.dtypes

df.head()

"""## 1. Data Cleaning

`TotalCharges` sering terbaca sebagai teks karena ada baris dengan spasi kosong (biasanya pelanggan baru dengan tenure 0 bulan).
"""

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
missing_before = df["TotalCharges"].isna().sum()
print(f"Jumlah TotalCharges kosong/invalid: {missing_before}")

# Baris dengan TotalCharges kosong biasanya pelanggan baru (tenure=0) -> isi dengan 0
df["TotalCharges"] = df["TotalCharges"].fillna(0)

# Ubah kolom Churn jadi biner (1/0) untuk perhitungan lebih mudah
df["ChurnFlag"] = df["Churn"].map({"Yes": 1, "No": 0})
df[["TotalCharges", "Churn", "ChurnFlag"]].head()

"""## 2. Exploratory Data Analysis (EDA)"""

overall_churn_rate = df["ChurnFlag"].mean() * 100
print(f"Churn rate keseluruhan: {overall_churn_rate:.1f}%")

"""### 2a. Churn rate per tipe kontrak"""

churn_by_contract = df.groupby("Contract")["ChurnFlag"].mean().sort_values(ascending=False) * 100
churn_by_contract

"""### 2b. Churn rate per rentang tenure (lama berlangganan, dalam bulan)"""

bins = [0, 6, 12, 24, 48, 72]
labels = ["0-6 bln", "7-12 bln", "13-24 bln", "25-48 bln", "49-72 bln"]
df["TenureGroup"] = pd.cut(df["tenure"], bins=bins, labels=labels, include_lowest=True)
churn_by_tenure = df.groupby("TenureGroup", observed=True)["ChurnFlag"].mean() * 100
churn_by_tenure

"""### 2c. Churn rate per metode pembayaran"""

churn_by_payment = df.groupby("PaymentMethod")["ChurnFlag"].mean().sort_values(ascending=False) * 100
churn_by_payment

"""### 2d. Rata-rata biaya bulanan: churn vs tidak"""

avg_charges = df.groupby("Churn")["MonthlyCharges"].mean()
avg_charges

"""## 3. Visualisasi"""

plt.style.use("seaborn-v0_8-whitegrid")

fig, ax = plt.subplots(figsize=(6, 4))
churn_by_contract.plot(kind="bar", color="#c0392b", ax=ax)
ax.set_title("Churn Rate per Tipe Kontrak")
ax.set_ylabel("Churn Rate (%)")
ax.set_xlabel("")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/1_churn_by_contract.png", dpi=150)
plt.show()

fig, ax = plt.subplots(figsize=(6, 4))
churn_by_tenure.plot(kind="bar", color="#2980b9", ax=ax)
ax.set_title("Churn Rate per Kelompok Tenure")
ax.set_ylabel("Churn Rate (%)")
ax.set_xlabel("")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/2_churn_by_tenure.png", dpi=150)
plt.show()

fig, ax = plt.subplots(figsize=(7, 4))
churn_by_payment.plot(kind="bar", color="#8e44ad", ax=ax)
ax.set_title("Churn Rate per Metode Pembayaran")
ax.set_ylabel("Churn Rate (%)")
ax.set_xlabel("")
plt.xticks(rotation=20, ha="right")
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/3_churn_by_payment.png", dpi=150)
plt.show()

fig, ax = plt.subplots(figsize=(6, 4))
df[df["Churn"] == "Yes"]["MonthlyCharges"].plot(kind="density", ax=ax, label="Churn", color="#c0392b")
df[df["Churn"] == "No"]["MonthlyCharges"].plot(kind="density", ax=ax, label="Tidak Churn", color="#27ae60")
ax.set_title("Distribusi Biaya Bulanan: Churn vs Tidak")
ax.set_xlabel("Monthly Charges")
ax.legend()
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/4_monthly_charges_distribution.png", dpi=150)
plt.show()

"""## 4. Draft Memo Insight

Jalankan cell di bawah untuk menghasilkan draf memo otomatis dari angka-angka di atas. Perhalus kalimatnya dengan gaya Anda sendiri sebelum dipakai di README GitHub.
"""

top_contract = churn_by_contract.index[0]
top_contract_rate = churn_by_contract.iloc[0]
lowest_tenure_rate = churn_by_tenure.iloc[0]
top_payment = churn_by_payment.index[0]
top_payment_rate = churn_by_payment.iloc[0]

memo = f"""
Churn rate keseluruhan pelanggan adalah {overall_churn_rate:.1f}%.

Temuan utama:
1. Kontrak "{top_contract}" punya churn rate tertinggi ({top_contract_rate:.1f}%),
   jauh di atas rata-rata keseluruhan.
2. Pelanggan di kelompok tenure "0-6 bln" churn paling tinggi ({lowest_tenure_rate:.1f}%)
   -> periode kritis retensi ada di awal berlangganan.
3. Metode pembayaran "{top_payment}" berasosiasi dengan churn rate tertinggi
   ({top_payment_rate:.1f}%).

Rekomendasi:
- Fokuskan program retensi pada pelanggan baru (<6 bulan) dengan kontrak
  bulanan, karena kombinasi ini paling berisiko churn.
- Pertimbangkan insentif migrasi ke kontrak tahunan pada 3 bulan pertama.
- Evaluasi pengalaman pembayaran untuk metode "{top_payment}" -
  kemungkinan ada friksi yang mendorong pelanggan keluar.

(Catatan: ini draft otomatis dari angka - perkuat dengan konteks bisnis
dan validasi asumsi sebelum dipakai sebagai keputusan nyata.)
"""
print(memo)

with open(f"{OUTPUT_DIR}/memo_insight.txt", "w") as f:
    f.write(memo)

print(f"Memo disimpan di '{OUTPUT_DIR}/memo_insight.txt'")